### ISSUE TITLE
Parse null value in array

### ISSUE THREAD

**Issue by ddway2** [tgockel/json-voorhees#73]
I have a JSON string like this:
` 
{
    "array" : [
        null,
        null,
        {
           "name" : "toto"
       }
   ]
}
`
And i use DSL to parse it in struct 
```cpp
jsonv::formats_builder()
    .type<cell>()
       .member("name", &cell::name)
    .type<my_array>()
        .member("array", &my_array::array)
        .register_container<std::vector<cell>>()
```
But when i tried to parse this example, i have an error :
`
jsonv::extraction_error: Extraction error at .array[0]: Unexpected type: expected object but found null.
`
Can i have a solution to parse null value ?

**Comment by tgockel** [comment]
The issue here is that the implementation of [`adapter_for`](http://tgockel.github.io/json-voorhees/classjsonv_1_1adapter__for.html) only understands how to extract from objects. The solution would be something like making the `cell` adapter type aware of how to extract from `null`. Does something like this make sense?

```
jsonv::formats_builder()
    .type<cell>()
       .member("name", &cell::name)
       .default_value(cell("no name")) // just some value here
       .default_on_null()
    .type<my_array>()
        .member("array", &my_array::array)
        .register_container<std::vector<cell>>()
```

This is similar to [`default_value`](http://tgockel.github.io/json-voorhees/serialization_builder_dsl.html#serialization_builder_dsl_ref_member_level_default_value) as a member in the DSL.

**Comment by ddway2** [comment]
Thank: i will test asap :)

**Comment by ddway2** [comment]
And of course, this is right solution for my problem

**Comment by tgockel** [comment]
I'm keeping this issue open as a reminder to actually implement the code.

**Comment by tgockel** [comment]
Minor change: Now uses `type_default_value` and `type_default_on_null` to resolve the ambiguity between defaulted members and defaulted types. Otherwise, it should all work.
